export const metadata = {
  title: "Sistema de gestion rrhh",
  description: "Generated by create next app @tobimonges",
};

export default function RootLayout({ children }) {
  return (
      <html lang="es">
      <head>
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
                  integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
                  crossOrigin="anonymous"
                  async
          ></script>
          <link
              href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
              crossOrigin="anonymous"
          />
      </head>
      <body>
      {children}

      </body>

      </html>
  );
}
